export const refs = {
  pagination: document.querySelector('#pagination'),
  containerMovies: document.querySelector('.collection'),
  form: document.querySelector('.form'),
  input: document.querySelector('.form__input'),
   home: document.querySelector('.js-nav-home-btn'),
  library: document.querySelector('.js-nav-library-btn'),
  logo: document.querySelector('.js-logo-btn'),
  watched: document.querySelector('.js-btn-watched'),
  queue: document.querySelector('.js-btn-queue'),
  librarySection: document.querySelector('.library'),
  header: document.querySelector('.header'),
  formEl: document.querySelector('.form'),
  galleryEl: document.querySelector('.gallery'),
};