export const refs = {
  paginationContainer: document.querySelector('.container_pagination'),
  pagination: document.querySelector('#pagination'),
  containerMovies: document.querySelector('.collection'),
  form: document.querySelector('.form'),
  input: document.querySelector('.form__input'),
  home: document.querySelector('.js-nav-home-btn'),
  library: document.querySelector('.js-nav-library-btn'),
  logo: document.querySelector('.js-logo-btn'),
  watched: document.querySelector('.js-btn-watched'),
  queue: document.querySelector('.js-btn-queue'),
  librarySection: document.querySelector('.library'),
  header: document.querySelector('.header'),
  formEl: document.querySelector('.form'),
  filter: document.querySelector('.section__filter'),
  galleryEl: document.querySelector('.gallery'),
  galleryContainerEl: document.querySelector('.gallery > .container'),
  emptyPicture: document.querySelector('.emptyPicture'),
  arrowRefs: document.querySelector('.return-arrow'),
  themBtn: document.querySelector('.dark-mode-icon'),
  sliderList: document.querySelector('.slider-list'),
  sliderSection: document.querySelector('.section-slider'),
  openModalBtn: document.querySelector('.footer-developed-by-link'),
  closeModalBtn: document.querySelector('.btn-close'),
  modalBackdrop: document.querySelector('.backdrop'),
  modal: document.querySelector('.modal'),
};
